name: Continuous Integration

permissions: write-all

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          sudo npm install -g pnpm 
          pnpm install
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Compile the Contracts
        run: pnpm hardhat compile

      - name: run mocha/chai for waffle test
        run: pnpm test

      - name: run format to make everything prettier
        run: pnpm format

      - name: run lint to check code consistency
        run: pnpm lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{github.head.ref}}
