name: Format

on:
  pull_request:
    branches: [develop, release/**]
    types: [synchronize]

jobs:
  format:
    name: Format and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
        node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - name: Install pnpm
        run: sudo npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install -D svelte prettier prettier-plugin-svelte eslint eslint-config-google typescript
          pnpm install -D eslint-config-prettier @typescript-eslint/parser @typescript-eslint/eslint-plugin
      - name: Format
        run: pnpm run format

      # - name: Lint
      #   run: npm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting changes
