name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install pnpm
        run: sudo npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm add svelte typescript
          pnpm add -D prettier prettier-plugin-tailwindcss eslint
          pnpm add -D @typescript-eslint/parser @typescript-eslint/eslint-plugin

      - name: Format
        run: pnpm format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}

      - name: Lint
        run: pnpm lint
