name: Test

on:
  push:
    branches: [master, release/*]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
        run: |
          sudo npm install -g pnpm 
          pnpm install --no-frozen-lockfile
          
      - name: Install Playwright
        uses: microsoft/playwright-github-action@v1

      - name: build project, 
        run: pnpm run build
        
      - name: Jest & Playwright Tests
        run: pnpm run test
