name: Test

on: 
  push:
    branches: [develop, release/*]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo npm install -g pnpm 
          pnpm install
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: microsoft/playwright-github-action@v1

      - name: build project, firebase serve and playwright tests
        run: |
          pnpm build:dev
          pnpm fserve:dev 1> /dev/null 2>&1 & pnpm test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


  