name: Waffle

on:
  push:
    branches: [develop, release/*]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo npm install -g pnpm 
          pnpm install
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: run mocha/chai for waffle test
        run: |
          # Run Waffle Test
